# Generated by Django 5.2.12 on 2026-03-30 10:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('theft', 'Theft / Vutsotsi'), ('burglary', 'Burglary / Ku ngheneriwa endlwini'), ('assault', 'Assault / Ku vuriwa'), ('robbery', 'Robbery / Ku khomeriwa'), ('property_damage', 'Property Damage / Ku onhakala ka xifaniso'), ('domestic_violence', 'Domestic Violence / Nghungu ya le kaya'), ('service_delivery', 'Service Delivery / Vukorhokeri'), ('other', "Other / Swin'wana")], max_length=50, unique=True)),
                ('icon', models.CharField(default='fas fa-exclamation-triangle', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Incident Category',
                'verbose_name_plural': 'Incident Categories',
            },
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_xitsonga', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('location_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('operating_hours', models.TextField()),
                ('is_satellite', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Police Station',
                'verbose_name_plural': 'Police Stations',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('reference_number', models.CharField(blank=True, help_text='SAPS case reference number', max_length=20, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('description_xitsonga', models.TextField(blank=True, null=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_description', models.TextField(help_text='Describe location using landmarks if GPS not available')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('has_photo_evidence', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending / Ku lindzela'), ('assigned', 'Assigned / Ku nyikiwile'), ('in_progress', 'In Progress / Ku endliwa'), ('resolved', 'Resolved / Ku lulamisiwile'), ('closed', 'Closed / Ku pfariwile')], default='pending', max_length=20)),
                ('assigned_officer', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_station', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.incidentcategory')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_text', models.TextField()),
                ('update_text_xitsonga', models.TextField(blank=True, null=True)),
                ('update_type', models.CharField(choices=[('status_change', 'Status Change'), ('officer_note', 'Officer Note'), ('user_followup', 'User Follow-up'), ('evidence_added', 'Evidence Added'), ('resolution', 'Resolution')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Update',
                'verbose_name_plural': 'Case Updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evidence/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('caption_xitsonga', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='cases.case')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence',
                'verbose_name_plural': 'Evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('message_xitsonga', models.TextField(blank=True)),
                ('notification_type', models.CharField(choices=[('status_update', 'Status Update'), ('reminder', 'Reminder'), ('alert', 'Alert'), ('info', 'Information')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('sent_via_whatsapp', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
