# Generated by Django 5.2.12 on 2026-04-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='caseupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='case',
            name='description_xitsonga',
        ),
        migrations.RemoveField(
            model_name='case',
            name='has_photo_evidence',
        ),
        migrations.RemoveField(
            model_name='caseupdate',
            name='update_text_xitsonga',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='caption_xitsonga',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message_xitsonga',
        ),
        migrations.RemoveField(
            model_name='policestation',
            name='name_xitsonga',
        ),
        migrations.AddField(
            model_name='case',
            name='description_ts',
            field=models.TextField(blank=True, null=True, verbose_name='Description in Xitsonga'),
        ),
        migrations.AddField(
            model_name='case',
            name='location_description_ts',
            field=models.TextField(blank=True, null=True, verbose_name='Location in Xitsonga'),
        ),
        migrations.AddField(
            model_name='case',
            name='title_ts',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title in Xitsonga'),
        ),
        migrations.AddField(
            model_name='caseupdate',
            name='update_text_ts',
            field=models.TextField(blank=True, null=True, verbose_name='Update in Xitsonga'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='caption_ts',
            field=models.CharField(blank=True, max_length=500, verbose_name='Caption in Xitsonga'),
        ),
        migrations.AddField(
            model_name='incidentcategory',
            name='name_ts',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name in Xitsonga'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_ts',
            field=models.TextField(blank=True, verbose_name='Message in Xitsonga'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ts',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title in Xitsonga'),
        ),
        migrations.AddField(
            model_name='policestation',
            name='address_ts',
            field=models.TextField(blank=True, verbose_name='Address in Xitsonga'),
        ),
        migrations.AddField(
            model_name='policestation',
            name='name_ts',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name in Xitsonga'),
        ),
        migrations.AddField(
            model_name='policestation',
            name='operating_hours_ts',
            field=models.TextField(blank=True, verbose_name='Hours in Xitsonga'),
        ),
        migrations.AlterField(
            model_name='case',
            name='location_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='caseupdate',
            name='update_text',
            field=models.TextField(verbose_name='Update in English'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message in English'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title in English'),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='address',
            field=models.TextField(verbose_name='Address in English'),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name in English'),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='operating_hours',
            field=models.TextField(verbose_name='Hours in English'),
        ),
    ]
